[tools]
direnv = "2.34.0"
fd = "10.1.0"
fzf = "latest"
go = "1.22.6"
helm = "3.15.3"
k9s = "0.32.5"
krew = "0.4.4"
ksops = "4.3.2"
kubectl = "1.28.15"
pre-commit = "3.8.0"
ripgrep = "14.1.0"
sops = "3.9.0"
terraform = "1.8.0"
terraform-docs = "0.18.0"
velero = "1.14.0"
viddy = "0.4.0"
yq = "4.44.3"
kubectx = "0.9.5"
just = "1.35.0"
pluto = "5.20.2"
act = "0.2.67"
httpie-go = "0.7.0"
argo = "3.6.0"
usage = "latest"
python = "3.12.2"
aws-sam-cli = "1.121.0"
tflint = "0.53.0"
yamllint = "1.35.1"
"go:github.com/peak/s5cmd/v2" = "master"
"pipx:s3cmd" = "latest"
zoxide = "latest"
"ubi:golang-migrate/migrate" = "v4.18.1"
"ubi:hasura/graphql-engine" = "v2.42.0"
"pipx:keepercommander" = "latest"
node = "latest"
uv = "latest"
"ubi:fujiapple852/trippy" = { version = "0.12.2", exe = "trip" }
istioctl = "1.19.6"
difftastic = "latest"
"ubi:merschformann/gotz" = "latest"
ruff = "latest"
"aqua:fluxcd/flux2" = "2.1.2"

[settings]
experimental = true
